export {default as Home} from "./home/home"
export {default as About} from "./about/about"
export {default as Portfolio} from "./portfolio/portfolio"
export {default as Contact} from "./contact/contact"
export {default as  Blogs} from "./blogs/blog"
