export const data = [
    {id:1,
    style:"one", 
    url:"Capitalize on low hanging fruit to identify a ballpark value added activity to beta test. Override the digital divide with additional clickthroughs from DevOps. Nano data tech immersion along the information highway. Love the support of Archtek peoples override.",
    per:"assets/bed.jpeg",
    name:"Brian Kain",
    styles:"two",
    urls:"Capitalize on low hanging fruit to identify a ballpark value added activity to beta test. Override the digital divide with additional clickthroughs from DevOps. Nano data tech immersion along the information highway. Love the support of Archtek peoples override.",
    pers:"assets/bed2.jpeg",
    names:"Issac Cole"}, 
    {id:2,
    style:"one", 
    url:"Capitalize on low hanging fruit to identify a ballpark value added activity to beta test. Override the digital divide with additional clickthroughs from DevOps. Nano data tech immersion along the information highway. Love the support of Archtek peoples override.",
    per:"assets/bed2.jpeg",
    name:"Isaac Cole",
    styles:"two",
    urls:"Capitalize on low hanging fruit to identify a ballpark value added activity to beta test. Override the digital divide with additional clickthroughs from DevOps. Nano data tech immersion along the information highway. Love the support of Archtek peoples override.",
    pers:"assets/bar.jpeg",
    names:"Michelle White"}, 
    {id:3,
    style:"one", 
    url:"Capitalize on low hanging fruit to identify a ballpark value added activity to beta test. Override the digital divide with additional clickthroughs from DevOps. Nano data tech immersion along the information highway. Love the support of Archtek peoples override.",
    per:"assets/bar.jpeg",
    name:"Michelle White",
    styles:"two",
    urls:"Capitalize on low hanging fruit to identify a ballpark value added activity to beta test. Override the digital divide with additional clickthroughs from DevOps. Nano data tech immersion along the information highway. Love the support of Archtek peoples override.",
    pers:"assets/kit.jpeg",
    names:"Abby Lance"}, 
    {id:4,
    style:"one", 
    url:"Capitalize on low hanging fruit to identify a ballpark value added activity to beta test. Override the digital divide with additional clickthroughs from DevOps. Nano data tech immersion along the information highway. Love the support of Archtek peoples override.",
    per:"assets/kit.jpeg",
    name:"Abby Lance",
    styles:"two",
    urls:"Capitalize on low hanging fruit to identify a ballpark value added activity to beta test. Override the digital divide with additional clickthroughs from DevOps. Nano data tech immersion along the information highway. Love the support of Archtek peoples override.",
    pers:"assets/lvr.jpeg",
    names:"Larry Pole"}, 
    {id:5,
    style:"one", 
    url:"Capitalize on low hanging fruit to identify a ballpark value added activity to beta test. Override the digital divide with additional clickthroughs from DevOps. Nano data tech immersion along the information highway. Love the support of Archtek peoples override.",
    per:"assets/lvr.jpeg",
    name:"Mike Tylla",
    styles:"two",
    urls:"Capitalize on low hanging fruit to identify a ballpark value added activity to beta test. Override the digital divide with additional clickthroughs from DevOps. Nano data tech immersion along the information highway. Love the support of Archtek peoples override.",
    pers:"assets/bed2.jpeg",
    names:"Brian Kain"}, 

]