export {default as Header} from './header/header'
export {default as Desc} from './desc/desc'
export {default as About} from './about/about'
export {default as Gallery} from './gallery/gallery'
export {default as How} from './how/how'
export {default as Employee} from './employee/employee'
export {default as Caro} from './caro/caro'
export {default as Blog} from './blog/blog'
export {default as Footer} from './footer/footer'
export {default as Testify} from './testimony/testify'
export {default as Navbar} from './navbar/navbar'
export {default as Test} from './caro/test'
export {default as Testimony} from './testimony/testimony'
export {default as Cursor} from './cursor/cursor'

